# Extrait de docker-compose.yml
services:
  db:  # <-- C'est le nom du service, donc vous utiliseriez 'db' dans l'URL
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: elaviradb
      POSTGRES_USER: mon_user # <-- C'est l'utilisateur à mettre dans .env
      POSTGRES_PASSWORD: mon_password # <-- C'est le mot de passe à mettre dans .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: