# docker-compose.yml
version: '3.8' # Optionnel, peut être supprimé pour les versions récentes de Docker Compose

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: elaviradb
      POSTGRES_USER: mon_user     # Assurez-vous que c'est bien 'mon_user'
      POSTGRES_PASSWORD: mon_password # Assurez-vous que c'est bien 'mon_password'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # Fait référence au volume nommé défini ci-dessous

volumes: # <-- CETTE SECTION ÉTAIT MANQUANTE !
  postgres_data: # <-- Définition du volume nommé 'postgres_data'